server {
    listen 8080;
    server_name _;

    return 301 https://$host:4443$request_uri;
}

server {
    listen 4443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Static game
	location /unity/ {
	    root /usr/share/nginx;
	    index index.html;
	}

    # Pre-compressed JavaScript
    location ~ ^/unity/.+\.js\.br$ {
        root /usr/share/nginx;
        gzip off;
        add_header Content-Encoding br;
        default_type application/javascript;
    }

    # Pre-compressed JavaScript
    location ~ ^/unity/.+\.js\.gz$ {
        root /usr/share/nginx;
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/javascript;
    }

    # Pre-compressed WebAssembly
    location ~ ^/unity/.+\.wasm\.gz$ {
        root /usr/share/nginx;
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/wasm;
    }

    # Pre-compressed data
    location ~ ^/unity/.+\.data\.gz$ {
        root /usr/share/nginx;
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/octet-stream;
    }

    # Everything else → application
    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
